version: '3.8'

services:
  botpress:
    build:
      context: .
      args:
        REPO_URL: BOTPRESS_REPO
        BRANCH: BOTPRESS_BRANCH
    container_name: botpress
    ports:
      - "BOTPRESS_PORT:3000"
    restart: unless-stopped
    volumes:
      - botpress_data:/botpress/data

volumes:
  botpress_data:
